# Generated by Django 6.0.4 on 2026-05-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_adicional_banco_adicional_numero_recibo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='numero_modulos_online',
            field=models.PositiveIntegerField(default=2, help_text='Cantidad de módulos para modalidad ONLINE. Se usa para el control de pagos por módulo.'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Pichincha'), ('guayaquil', 'Guayaquil'), ('produbanco', 'Produbanco'), ('banco_pacifico', 'Banco del Pacífico'), ('otro', 'Otro / Payphone')], max_length=30),
        ),
        migrations.AlterField(
            model_name='abono',
            name='cuenta_para_saldo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='abono',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abono',
            name='numero_modulo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abono',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='abono',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono'), ('por_modulo', 'Por módulo'), ('pago_completo', 'Pago completo'), ('recuperacion', 'Recuperación')], default='abono', max_length=20),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Pichincha'), ('guayaquil', 'Guayaquil'), ('produbanco', 'Produbanco'), ('banco_pacifico', 'Banco del Pacífico'), ('otro', 'Otro / Payphone')], help_text='Banco usado (solo si el método es Transferencia bancaria o Tarjeta).', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='numero_modulos',
            field=models.PositiveIntegerField(default=4, help_text='Cantidad de módulos para modalidad PRESENCIAL. Se usa para el control de pagos por módulo.'),
        ),
        migrations.CreateModel(
            name='AssistantQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de consulta asistente',
                'verbose_name_plural': 'Registros de consultas asistente',
                'ordering': ['-created'],
            },
        ),
    ]
