# Generated by Django 6.0.4 on 2026-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_curso_numero_modulos_online_alter_abono_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Pichincha'), ('guayaquil', 'Guayaquil'), ('produbanco', 'Produbanco'), ('banco_pacifico', 'Banco del Pacífico'), ('payphone', 'Payphone')], max_length=30),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Pichincha'), ('guayaquil', 'Guayaquil'), ('produbanco', 'Produbanco'), ('banco_pacifico', 'Banco del Pacífico'), ('payphone', 'Payphone')], help_text='Banco usado (solo si el método es Transferencia bancaria o Tarjeta).', max_length=20),
        ),
    ]
