# Generated by Django 6.0.5 on 2026-05-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_cierrecurso_matriculaarchivada_abonoarchivado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecurso',
            name='limpio_directorio',
            field=models.BooleanField(default=False, help_text='True si en este cierre se borraron además los estudiantes huérfanos del directorio.'),
        ),
        migrations.AddField(
            model_name='cierrecurso',
            name='modalidad_global',
            field=models.CharField(blank=True, help_text='Solo para alcance="global": presencial, online o "" (todas las modalidades).', max_length=20),
        ),
        migrations.AddField(
            model_name='cierrecurso',
            name='total_estudiantes_archivados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EstudianteArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_original_id', models.PositiveIntegerField(blank=True, help_text='ID del estudiante original (referencia auditiva).', null=True)),
                ('cedula', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('nivel_formacion', models.CharField(blank=True, max_length=80)),
                ('titulo_profesional', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('creado_original', models.DateTimeField(blank=True, help_text='Fecha en que se registró originalmente el estudiante.', null=True)),
                ('archivado_en', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_archivados', to='academia.cierrecurso')),
            ],
            options={
                'verbose_name': 'Estudiante archivado',
                'verbose_name_plural': 'Estudiantes archivados',
                'ordering': ['-archivado_en', 'apellidos', 'nombres'],
                'indexes': [models.Index(fields=['cedula'], name='academia_es_cedula_2d4d2e_idx'), models.Index(fields=['cierre'], name='academia_es_cierre__958346_idx')],
            },
        ),
    ]
