# Generated by Django 6.0.5 on 2026-05-20 04:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0022_cierrecurso_limpio_directorio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(blank=True, help_text='Mes (1-12). Si es nulo, el cierre cubre todo el año.', null=True)),
                ('etiqueta', models.CharField(blank=True, help_text='Etiqueta libre (ej. "Corte Mayo 2026").', max_length=80)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('ingreso_abonos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Abonos vivos del periodo.', max_digits=12)),
                ('ingreso_abonos_archivados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Abonos de cursos cerrados (archivados) del periodo.', max_digits=12)),
                ('ingreso_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ventas/comprobantes manuales del periodo.', max_digits=12)),
                ('ingreso_adicionales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adicionales (certificados, supletorios, camisas) del periodo.', max_digits=12)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('egreso_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('egresos_detalle_json', models.TextField(blank=True, help_text='JSON con el desglose de egresos por categoría al momento del cierre.')),
                ('balance_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ingreso_total - egreso_total.', max_digits=12)),
                ('cierres_curso_incluidos', models.PositiveIntegerField(default=0, help_text='Cuántos cierres de curso cayeron dentro de este periodo.')),
                ('monto_cierres_curso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cobrado en los cierres de curso de este periodo.', max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_admin_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre administrativo',
                'verbose_name_plural': 'Cierres administrativos',
                'ordering': ['-anio', '-mes', '-fecha_cierre'],
            },
        ),
    ]
