# Generated by Django 6.0.5 on 2026-05-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0023_cierreadministrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadacurso',
            name='descripcion_otros',
            field=models.CharField(blank=True, help_text='Días personalizados (solo se usa cuando la descripción es "Otros").', max_length=120),
        ),
        migrations.AlterField(
            model_name='jornadacurso',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad (presencial) o plataforma (online). Se mantiene sincronizada con la sede.', max_length=100),
        ),
        migrations.AlterField(
            model_name='jornadacurso',
            name='descripcion',
            field=models.CharField(choices=[('lun_mie_vie', 'Lun, Mié, Vie.'), ('mar_mie_jue', 'Mar, Mié, Jue.'), ('mar_jue', 'Martes y Jueves'), ('sabados_intensivos', 'Sábados Intensivos'), ('domingos_intensivos', 'Domingos Intensivos'), ('otros', 'Otros (especificar)')], help_text='Días en que se dicta la jornada.', max_length=200),
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sede o ciudad (ej. Guayaquil, Quito, Caracas).', max_length=100)),
                ('pais', models.CharField(default='Ecuador', help_text='País donde está la sede (ej. Ecuador, Venezuela).', max_length=80)),
                ('direccion', models.CharField(blank=True, help_text='Dirección física de la sede (opcional).', max_length=200)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto de la sede (opcional).', max_length=40)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en los listados (menor primero).')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada, no aparece para elegir en jornadas nuevas, pero las jornadas existentes que ya la usan se conservan.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sede / Campus',
                'verbose_name_plural': 'Sedes / Campus',
                'ordering': ['pais', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'pais'), name='sede_unica_nombre_pais')],
            },
        ),
        migrations.AddField(
            model_name='jornadacurso',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede/campus donde se dicta (presencial). Reemplaza al texto libre de ciudad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas', to='academia.sede'),
        ),
    ]
