# Generated by Django 6.0.4 on 2026-05-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0025_poblar_sedes_desde_ciudades'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicional_original_id', models.PositiveIntegerField(blank=True, help_text='ID del adicional original (referencia auditiva).', null=True)),
                ('tipo_adicional', models.CharField(max_length=30)),
                ('tipo_adicional_label', models.CharField(blank=True, max_length=50)),
                ('persona_nombre', models.CharField(blank=True, max_length=200)),
                ('persona_cedula', models.CharField(blank=True, max_length=20)),
                ('persona_celular', models.CharField(blank=True, max_length=30)),
                ('origen_label', models.CharField(blank=True, max_length=30)),
                ('curso_nombre', models.CharField(blank=True, max_length=150)),
                ('modalidad', models.CharField(blank=True, max_length=20)),
                ('talla_camiseta', models.CharField(blank=True, max_length=4)),
                ('numero_modulo', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=20)),
                ('metodo_pago_label', models.CharField(blank=True, max_length=40)),
                ('banco', models.CharField(blank=True, max_length=30)),
                ('banco_label', models.CharField(blank=True, max_length=40)),
                ('numero_recibo', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por_nombre', models.CharField(blank=True, max_length=120)),
                ('creado_original', models.DateTimeField(blank=True, null=True)),
                ('archivado_en', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(blank=True, help_text='Cierre asociado (puede ser nulo si se archivó al limpiar directorio).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionales_archivados', to='academia.cierrecurso')),
            ],
            options={
                'verbose_name': 'Adicional archivado',
                'verbose_name_plural': 'Adicionales archivados',
                'ordering': ['-archivado_en', '-fecha'],
                'indexes': [models.Index(fields=['persona_cedula'], name='academia_ad_persona_5ccfc1_idx'), models.Index(fields=['cierre'], name='academia_ad_cierre__2a36ee_idx')],
            },
        ),
    ]
