# Generated by Django 6.0.5 on 2026-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0027_adicional_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('abono', 'Abono'), ('pago_completo', 'Pago completo'), ('modulo', 'Módulo')], help_text='Cómo se cobra el curso al matricular: Abono (parcial), Pago completo (valor neto) o Módulo (un módulo). Define el monto inicial registrado en la sección de Abonos.', max_length=20),
        ),
    ]
