# Generated by Django 6.0.4 on 2026-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0028_matricula_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='es_ciclo_corto',
            field=models.BooleanField(default=False, help_text='Indica si el curso es de ciclo corto (2 semanas).'),
        ),
    ]
