# Generated by Django 6.0.6 on 2026-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0029_curso_es_ciclo_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='tipo_adicional',
            field=models.CharField(choices=[('cert_matricula', 'Certificado de matrícula'), ('cert_asistencia', 'Certificado de asistencia'), ('cert_antiguo', 'Certificado antiguo'), ('examen_supletorio', 'Examen supletorio'), ('camisa', 'Camisa'), ('practicas', 'Prácticas'), ('otros', 'Otros')], help_text='Tipo de servicio/producto adicional.', max_length=30),
        ),
    ]
