# Generated by Django 6.0.6 on 2026-06-14 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0030_alter_adicional_tipo_adicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto del aviso (ej. "Mantenimiento del sistema").', max_length=140)),
                ('contenido', models.TextField(help_text='Cuerpo del aviso. Admite formato: negrita, cursiva, subrayado, listas y colores.')),
                ('tema', models.CharField(choices=[('info', 'Azul (informativo)'), ('success', 'Verde (positivo)'), ('warning', 'Naranja (atención)'), ('danger', 'Rojo (urgente)'), ('navy', 'Azul marino (institucional)')], default='info', help_text='Color del marco/encabezado del aviso.', max_length=10)),
                ('fecha_inicio', models.DateTimeField(help_text='Desde cuándo empieza a mostrarse el aviso.')),
                ('fecha_fin', models.DateTimeField(help_text='Hasta cuándo se muestra. Al pasar esta fecha desaparece solo.')),
                ('activo', models.BooleanField(default=True, help_text='Si se desmarca, el aviso se oculta aunque esté en vigencia.')),
                ('fijado', models.BooleanField(default=False, help_text='Si se marca, aparece de primero por encima de los demás.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso / Anuncio',
                'verbose_name_plural': 'Avisos / Anuncios',
                'ordering': ['-fijado', '-fecha_inicio', '-creado'],
            },
        ),
    ]
