# Generated by Django 6.0.6 on 2026-06-14 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0031_aviso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto de la nota (ej. "Llamar al proveedor").', max_length=140, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Escribe aquí lo que necesitas recordar o comunicar.', verbose_name='Nota')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha', models.DateField(help_text='Fecha del recordatorio (a qué día corresponde).', verbose_name='Fecha')),
                ('fecha_vencimiento', models.DateField(help_text='Hasta cuándo es válido el recordatorio.', verbose_name='Fecha de vencimiento')),
                ('leido', models.BooleanField(default=False, help_text='Se marca cuando el destinatario lo ve / lo da por enterado.', verbose_name='Leído')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destinatario', models.ForeignKey(help_text='Usuario al que le quieres notificar este recordatorio.', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Notificar a')),
            ],
            options={
                'verbose_name': 'Recordatorio / Borrador',
                'verbose_name_plural': 'Recordatorios / Borradores',
                'ordering': ['leido', '-fecha', '-creado'],
            },
        ),
    ]
