# Generated by Django 6.0.4 on 2026-06-15 00:30

from django.db import migrations


from django.core.management import call_command

def crear_grupos_y_roles(apps, schema_editor):
    try:
        call_command('setup_roles')
    except Exception:
        # En una base de datos nueva, los permisos aún no están totalmente
        # poblados en este punto de la migración, así que setup_roles puede
        # quedar incompleto. Es ESPERADO y NO es un error: se completa al
        # correr `python manage.py init_proyecto` (o `setup_roles`) después
        # de que termine `migrate`.
        print("Nota: los roles se completan con 'python manage.py init_proyecto' "
              "tras finalizar migrate.")

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0032_recordatorio'),
    ]

    operations = [
        migrations.RunPython(crear_grupos_y_roles, reverse_code=migrations.RunPython.noop),
    ]
