# Generated by Django 6.0.4 on 2026-06-24 04:06

from django.db import migrations

def merge_names(apps, schema_editor):
    Estudiante = apps.get_model('academia', 'Estudiante')
    for est in Estudiante.objects.all():
        n = (est.nombres or '').strip()
        a = (est.apellidos or '').strip()
        # Forma natural: Nombres Apellidos
        est.nombres = f"{n} {a}".strip()
        est.save()

    EstudianteArchivado = apps.get_model('academia', 'EstudianteArchivado')
    for est in EstudianteArchivado.objects.all():
        n = (est.nombres or '').strip()
        a = (est.apellidos or '').strip()
        est.nombres = f"{n} {a}".strip()
        est.save()

    PersonaExterna = apps.get_model('academia', 'PersonaExterna')
    for pe in PersonaExterna.objects.all():
        n = (pe.nombres or '').strip()
        a = (pe.apellidos or '').strip()
        pe.nombres = f"{n} {a}".strip()
        pe.save()

    Matricula = apps.get_model('academia', 'Matricula')
    for mat in Matricula.objects.all():
        n = (mat.fact_nombres or '').strip()
        a = (mat.fact_apellidos or '').strip()
        if n or a:
            mat.fact_nombres = f"{n} {a}".strip()
            mat.save()

    MatriculaArchivada = apps.get_model('academia', 'MatriculaArchivada')
    for mat in MatriculaArchivada.objects.all():
        n = (mat.fact_nombres or '').strip()
        a = (mat.fact_apellidos or '').strip()
        if n or a:
            mat.fact_nombres = f"{n} {a}".strip()
            mat.save()

def reverse_merge(apps, schema_editor):
    pass  # We cannot safely reverse this data migration

class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0033_auto_crear_grupos'),
    ]

    operations = [
        migrations.RunPython(merge_names, reverse_merge),
    ]
