# Generated by Django 6.0.4 on 2026-06-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0034_merge_nombres_apellidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombres'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='estudiantearchivado',
            options={'ordering': ['-archivado_en', 'nombres'], 'verbose_name': 'Estudiante archivado', 'verbose_name_plural': 'Estudiantes archivados'},
        ),
        migrations.AlterModelOptions(
            name='matriculaarchivada',
            options={'ordering': ['cierre', 'nombres'], 'verbose_name': 'Matrícula archivada', 'verbose_name_plural': 'Matrículas archivadas'},
        ),
        migrations.AlterModelOptions(
            name='personaexterna',
            options={'ordering': ['nombres'], 'verbose_name': 'Persona externa', 'verbose_name_plural': 'Personas externas'},
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='fact_apellidos',
        ),
        migrations.RemoveField(
            model_name='adicionalarchivado',
            name='fact_apellidos',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='fact_apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiantearchivado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='fact_apellidos',
        ),
        migrations.RemoveField(
            model_name='matriculaarchivada',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='matriculaarchivada',
            name='fact_apellidos',
        ),
        migrations.RemoveField(
            model_name='personaexterna',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='adicional',
            name='fact_nombres',
            field=models.CharField(blank=True, help_text='Nombres del titular de la factura.', max_length=200),
        ),
        migrations.AlterField(
            model_name='adicionalarchivado',
            name='fact_nombres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fact_nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres y Apellidos (factura)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='estudiantearchivado',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fact_nombres',
            field=models.CharField(blank=True, help_text='Nombres del titular de la factura.', max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaarchivada',
            name='fact_nombres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='matriculaarchivada',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='personaexterna',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres y Apellidos'),
        ),
    ]
