# Generated by Django 6.0.4 on 2026-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0035_remove_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='banco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco usado (solo si el método es Transferencia bancaria o Tarjeta).', max_length=50),
        ),
    ]
