# Generated by Django 5.1.15 on 2026-06-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0036_alter_abono_banco_alter_adicional_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='banco_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='abono',
            name='metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta')], max_length=20),
        ),
        migrations.AddField(
            model_name='abono',
            name='monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('abono', 'Abono'), ('pago_completo', 'Pago completo'), ('modulo', 'Módulo'), ('abono_modulo', 'Abono / Módulo')], help_text='Cómo se cobra el curso al matricular: Abono (parcial), Pago completo (valor neto) o Módulo (un módulo). Define el monto inicial registrado en la sección de Abonos.', max_length=20),
        ),
    ]
