# Generated by Django 5.1.15 on 2026-06-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0037_abono_banco_2_abono_metodo_2_abono_monto_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='banco_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adicional',
            name='banco_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adicional',
            name='metodo_pago_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito')], max_length=20),
        ),
        migrations.AddField(
            model_name='adicional',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito')], max_length=20),
        ),
        migrations.AddField(
            model_name='adicional',
            name='monto_pago_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='monto_pago_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adicional',
            name='tipo_cobro',
            field=models.CharField(choices=[('un_solo_metodo', 'Un solo método'), ('mixto', 'Mixto (Dividir en dos pagos)')], default='un_solo_metodo', help_text='Distribución del pago', max_length=20),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='banco_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='banco_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='metodo_pago_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='metodo_pago_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='monto_pago_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='monto_pago_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adicionalarchivado',
            name='tipo_cobro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adicionalarchivado',
            name='banco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adicionalarchivado',
            name='banco_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('abono', 'Abono'), ('pago_completo', 'Pago completo'), ('abono_modulo', 'Abono / Módulo')], help_text='Cómo se cobra el curso al matricular: Abono (parcial), Pago completo (valor neto) o Módulo (un módulo). Define el monto inicial registrado en la sección de Abonos.', max_length=20),
        ),
    ]
