# Generated by Django 5.1.15 on 2026-06-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0038_adicional_banco_1_adicional_banco_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='vendedora',
            field=models.ForeignKey(blank=True, help_text='Usuario (asesora) que concretó la venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_vendidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
