# Generated by Django 5.1.15 on 2026-06-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0040_estudiante_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='fact_correo',
            field=models.CharField(blank=True, help_text='Correo electrónico para enviar la factura.', max_length=254),
        ),
        migrations.AlterField(
            model_name='adicionalarchivado',
            name='fact_correo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fact_correo',
            field=models.CharField(max_length=254, verbose_name='Correo electrónico (factura)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiantearchivado',
            name='correo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fact_correo',
            field=models.CharField(blank=True, help_text='Correo electrónico para enviar la factura.', max_length=254),
        ),
        migrations.AlterField(
            model_name='matriculaarchivada',
            name='correo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='matriculaarchivada',
            name='fact_correo',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personaexterna',
            name='correo',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
