# Generated by Django 5.1.15 on 2026-06-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0041_alter_adicional_fact_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantearchivado',
            name='registrado_por_nombre',
            field=models.CharField(blank=True, help_text='Persona que registró originalmente al estudiante.', max_length=120),
        ),
        migrations.AddField(
            model_name='estudiantearchivado',
            name='vendedora_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la vendedora de la última matrícula.', max_length=150),
        ),
        migrations.AddField(
            model_name='matriculaarchivada',
            name='vendedora_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la vendedora de la matrícula.', max_length=150),
        ),
    ]
