# Generated by Django 5.1.15 on 2026-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0043_recuperacionpendiente_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperacionpendiente',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('laptops_computadora', 'Laptops / Computadora'), ('celulares_tablet', 'Celulares / Tablet'), ('impresora', 'Impresora'), ('consolas', 'Consolas de videojuegos'), ('lavadora', 'Lavadora'), ('nevera', 'Nevera'), ('secadora', 'Secadora'), ('cocina', 'Cocina')], help_text='Tipo de equipo a recuperar (solo para Servicio Técnico)', max_length=50, null=True),
        ),
    ]
