# Generated by Django 5.1.15 on 2026-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0044_alter_recuperacionpendiente_tipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombrar_modulos',
            field=models.BooleanField(default=False, help_text='Indica si los módulos tendrán nombres personalizados.'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombres_modulos',
            field=models.JSONField(blank=True, default=dict, help_text='Diccionario con los nombres de los módulos por modalidad. Ej: {"presencial": ["M1"], "online": ["M1"]}'),
        ),
    ]
