# Generated by Django 6.0.6 on 2026-07-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0045_curso_nombrar_modulos_curso_nombres_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono'), ('por_modulo', 'Abono + Módulo'), ('solo_modulo', 'Solo Módulo'), ('pago_completo', 'Pago completo'), ('recuperacion', 'Recuperación')], default='abono', max_length=20),
        ),
        migrations.AlterField(
            model_name='recuperacionpendiente',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('laptops_computadora', 'Laptops / Computadora'), ('celulares_tablet', 'Celulares / Tablet'), ('impresora', 'Impresora'), ('consolas_videojuegos', 'Consolas de videojuegos'), ('lavadora', 'Lavadora'), ('nevera', 'Nevera'), ('secadora', 'Secadora'), ('cocina', 'Cocina')], help_text='Clase específica a recuperar (para Servicio Técnico o Línea Blanca).', max_length=50, null=True),
        ),
    ]
