# Generated by Django 6.0.7 on 2026-07-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0046_alter_abono_tipo_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaManualRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la hoja de recaudación a la que aplica el monto.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_manuales', to='academia.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_manuales_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota manual de recaudación',
                'verbose_name_plural': 'Cuotas manuales de recaudación',
                'unique_together': {('matricula', 'fecha')},
            },
        ),
    ]
