# Generated by Django 5.1.15 on 2026-07-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0047_cuotamanualrecaudacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecurso',
            name='alcance',
            field=models.CharField(choices=[('jornada', 'Una jornada específica'), ('curso', 'Todo el curso (todas las jornadas)'), ('global', 'Cierre global (todos los cursos)'), ('manual', 'Manual por estudiante')], default='jornada', max_length=20),
        ),
    ]
