# Generated by Django 6.0.7 on 2026-07-21 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0049_backfill_estudiantes_cierre_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperacionpendiente',
            name='abono',
            field=models.ForeignKey(blank=True, help_text='Pago asociado a esta recuperación (si ya se cobró).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones', to='academia.abono'),
        ),
    ]
