# Generated by Django 6.0.7 on 2026-07-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0050_recuperacion_abono_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuperacionpendiente',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha pactada para que el estudiante recupere la clase.', null=True),
        ),
    ]
