# Generated by Django 6.0.7 on 2026-08-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0054_jornadacurso_feriado_aplicado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(help_text='Nombre visible del usuario al momento de la actividad.', max_length=150)),
                ('categoria', models.CharField(choices=[('acceso', 'Acceso'), ('consulta', 'Consulta'), ('creacion', 'Creación'), ('edicion', 'Edición'), ('eliminacion', 'Eliminación'), ('pago', 'Pago'), ('exportacion', 'Exportación'), ('administracion', 'Administración')], default='consulta', max_length=20)),
                ('accion', models.CharField(max_length=220)),
                ('detalle', models.TextField(blank=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('estado_http', models.PositiveSmallIntegerField(default=200)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de usuario',
                'verbose_name_plural': 'Actividades de usuarios',
                'ordering': ['-creado', '-pk'],
                'indexes': [models.Index(fields=['usuario', 'creado'], name='actividad_usuario_fecha_idx'), models.Index(fields=['categoria', 'creado'], name='actividad_categoria_fecha_idx')],
            },
        ),
    ]
