# Generated by Django 6.0.7 on 2026-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0055_actividadusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.CharField(choices=[('princesa', 'Princesa'), ('corona', 'Corona'), ('pollito', 'Pollito'), ('leon', 'León'), ('mujer_rubia', 'Mujer rubia'), ('pelirroja_clara', 'Mujer pelirroja clara'), ('mujer_afro_castana', 'Mujer afro castaña'), ('latina', 'Latina'), ('morena', 'Morena'), ('pelirroja_morena', 'Mujer morena pelirroja'), ('mulata', 'Mulata'), ('pacman', 'Pac-Man'), ('gorra_mario', 'Gorra de Mario'), ('princesa_peach', 'Princesa Peach'), ('logo_formacion', 'Logo Formación Profesional')], default='corona', max_length=32),
        ),
    ]
