# Generated by Django 6.0.7 on 2026-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0056_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='portada',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('mariposas', 'Mariposas'), ('castillo', 'Castillo'), ('paisaje', 'Paisaje natural')], default='institucional', max_length=32),
        ),
    ]
