# Generated by Django 6.0.7 on 2026-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0057_perfilusuario_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.CharField(choices=[('princesa', 'Princesa'), ('corona', 'Corona'), ('pollito', 'Pollito'), ('leon', 'León'), ('mujer_rubia', 'Mujer rubia'), ('pelirroja_clara', 'Mujer pelirroja clara'), ('mujer_afro_castana', 'Mujer afro castaña'), ('latina', 'Latina'), ('morena', 'Morena'), ('pelirroja_corona', 'Cabello rojo con corona'), ('morena_corona', 'Morena con corona'), ('pelirroja_morena', 'Mujer morena pelirroja'), ('mulata', 'Mulata'), ('pacman', 'Pac-Man'), ('gorra_mario', 'Gorra de Mario'), ('gorra_luigi', 'Gorra de Luigi'), ('caballo', 'Caballo'), ('dinosaurio', 'Dinosaurio'), ('tigre', 'Tigre'), ('perro', 'Perro'), ('gato', 'Gato'), ('princesa_peach', 'Princesa Peach'), ('logo_formacion', 'Logo Formación Profesional')], default='corona', max_length=32),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='portada',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('mariposas', 'Mariposas'), ('castillo', 'Castillo'), ('paisaje', 'Paisaje natural'), ('mundo_magico_nieve', 'Mundo mágico en la nieve'), ('mundo_champinon', 'Mundo champiñón')], default='institucional', max_length=32),
        ),
    ]
