# Generated by Django 6.0.7 on 2026-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0058_alter_perfilusuario_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='descripcion_personal',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='hobbies_favoritos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='intereses_personales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='musica_favorita',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='peliculas_favoritas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
