# Generated by Django 6.0.7 on 2026-08-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0059_perfilusuario_mural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmistadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada')], db_index=True, default='pendiente', max_length=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_amistad_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_como_usuario_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_como_usuario_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amistad de usuario',
                'verbose_name_plural': 'Amistades de usuarios',
                'ordering': ['-actualizada', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('usuario_a', 'usuario_b'), name='amistad_par_usuario_unico'), models.CheckConstraint(condition=models.Q(('usuario_a__lt', models.F('usuario_b'))), name='amistad_usuarios_ordenados')],
            },
        ),
        migrations.CreateModel(
            name='MeGustaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta_otorgados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Me gusta de perfil',
                'verbose_name_plural': 'Me gusta de perfiles',
                'ordering': ['-creado', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'perfil'), name='me_gusta_perfil_unico'), models.CheckConstraint(condition=models.Q(('usuario', models.F('perfil')), _negated=True), name='me_gusta_perfil_no_propio')],
            },
        ),
    ]
