# Generated by Django 6.0.7 on 2026-09-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0065_seleccion_jornadas_recaudacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacionPagoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('ultimo_error', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('abono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion_correo', to='academia.abono')),
            ],
        ),
    ]
