# Generated by Django 6.0.7 on 2026-09-06 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0066_confirmacionpagocorreo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=300)),
                ('curso_nombre', models.CharField(max_length=300)),
                ('jornada_anterior', models.TextField()),
                ('jornada_nueva', models.TextField()),
                ('motivo', models.CharField(max_length=500)),
                ('responsable_nombre', models.CharField(max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_jornada', to='academia.matricula')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado', '-pk'],
            },
        ),
    ]
