# Generated by Django 6.0.7 on 2026-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0068_avatares_personajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='portada',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('mariposas', 'Mariposas'), ('castillo', 'Castillo'), ('paisaje', 'Paisaje natural'), ('mundo_magico_nieve', 'Mundo mágico en la nieve'), ('mundo_champinon', 'Mundo champiñón'), ('nieve_frozen', 'Nieve estilo Frozen'), ('castillo_disney', 'Castillo estilo Disney'), ('pantano_shrek', 'Pantano estilo Shrek')], default='institucional', max_length=32),
        ),
    ]
