# Generated by Django 6.0.8 on 2026-09-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0073_matricula_modulo_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='tipo_matricula',
            field=models.CharField(choices=[('reserva_abono', 'Reserva / Abono'), ('inscripcion_gratis', 'Inscripción (gratis)'), ('reserva_modulo_1', 'Reserva + Módulo 1'), ('programa_completo', 'Programa Completo'), ('otros', 'Otros')], default='programa_completo', help_text='Tipo de matrícula contratada por el estudiante.', max_length=30),
        ),
    ]
