# Generated by Django 6.0.8 on 2026-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0074_tipos_matricula_otros_inscripcion_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperacionpendiente',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('laptops_computadora', 'Laptops / Computadora'), ('celulares_tablet', 'Celulares / Tablet'), ('impresora', 'Impresora'), ('consolas_videojuegos', 'Consolas de videojuegos'), ('lavadora', 'Lavadora'), ('nevera', 'Nevera'), ('secadora', 'Secadora'), ('cocina', 'Cocina'), ('no_especificar', 'No especificar')], help_text='Clase específica a recuperar (para Servicio Técnico o Línea Blanca).', max_length=50, null=True),
        ),
    ]
