# Generated by Django 6.0.8 on 2026-09-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0075_recuperacion_tipo_equipo_no_especificar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta / Link de pago')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta / Link de pago')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='banco',
            field=models.CharField(blank=True, help_text='Banco o app usado (solo si el método es Depósito, Transferencia bancaria o Tarjeta / Link de pago).', max_length=50),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta / Link de pago')], default='efectivo', help_text='Forma de pago.', max_length=20),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='metodo_pago_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta / Link de pago')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta / Link de pago')], max_length=20),
        ),
    ]
