# Generated by Django 6.0.8 on 2026-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0076_metodo_pago_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='numero_factura',
            field=models.CharField(blank=True, default='', help_text='Número de la factura emitida (solo números).', max_length=20),
        ),
        migrations.AddField(
            model_name='matriculaarchivada',
            name='numero_factura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
