# Generated by Django 6.0.8 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0077_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_registro',
            field=models.CharField(blank=True, choices=[('central_1', 'Central 1'), ('central_2', 'Central 2'), ('central_ia', 'Central IA'), ('venta_presencial', 'Venta Presencial'), ('seguimiento', 'Seguimiento')], help_text='Origen del registro: Central 1, Central 2, Central IA, Venta Presencial o Seguimiento.', max_length=20, null=True, verbose_name='Tipo de registro'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_registro',
            field=models.CharField(blank=True, choices=[('central_1', 'Central 1'), ('central_2', 'Central 2'), ('central_ia', 'Central IA'), ('venta_presencial', 'Venta Presencial'), ('seguimiento', 'Seguimiento')], help_text='Origen del registro: Central 1, Central 2, Central IA, Venta Presencial o Seguimiento.', max_length=20),
        ),
    ]
