# Generated by Django 6.0.8 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0078_tipo_registro_venta_presencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='color_registro',
            field=models.CharField(blank=True, choices=[('azul', 'Azul'), ('naranja', 'Naranja'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('rosado', 'Rosado'), ('morado', 'Morado'), ('lila', 'Lila'), ('blanco', 'Blanco')], default='', help_text='Color de las filas que registra en el Registro Estudiantil. Solo lo cambia un administrador. Vacío: el sistema elige uno.', max_length=20, verbose_name='Color en el Registro Estudiantil'),
        ),
    ]
