# Generated by Django 6.0.8 on 2026-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0079_perfil_color_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='valor_anterior_online',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor que tenía antes el curso online (USD). Opcional.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='valor_anterior_presencial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor que tenía antes el curso presencial (USD). Opcional.', max_digits=10, null=True),
        ),
    ]
